MobileStoreWebsite/MobileSoreWebsite/Controllers/SearchController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MobileStoreBLL;
using MobileStoreBLL.BLL;
using System.Data.Entity;
using MobileStoreBLL.ViewModel;

namespace MobileSoreWebsite.Controllers
{
    public class SearchController : Controller
    {
        private MOBILESTOREEntities db = new MOBILESTOREEntities();
        SanPhamBLL spBLL = new SanPhamBLL();
        public ActionResult Index()
        {
            ChiTietSanPham ctsp = spBLL.Create();
            ViewBag.sp_producer = new SelectList(ctsp.DSHangSanXuat, "hsx_id", "hsx_name");
            ViewBag.sp_type = new SelectList(ctsp.DSLoaiSanPham, "lsp_id", "lsp_name");
            ViewBag.sp_status = new SelectList(ctsp.DSTinhTrangSanPham, "tt_id", "tt_name");
            return View();
        }

        
        public ActionResult Result(string sp_type, string sp_status, string sp_producer, string sp_highestPrice, string sp_lowestPrice, string keyWord)
        {
            bool Btype, Bstatus, Bproducer, BhighestPrice, BlowestPrice;
            BlowestPrice = !String.IsNullOrEmpty(sp_lowestPrice);
            BhighestPrice = !String.IsNullOrEmpty(sp_highestPrice);
            Btype = !String.IsNullOrEmpty(sp_type);
            Bstatus = !String.IsNullOrEmpty(sp_status);
            Bproducer = !String.IsNullOrEmpty(sp_producer);
                        
            int type = 0, status = 0, producer = 0, highestPrice = 0, lowestPrice = 0;
            if (Btype)
                type = Int32.Parse(sp_type);
            if (Bstatus)
                status = Int32.Parse(sp_status);
            if (Bproducer)
                producer = Int32.Parse(sp_producer);
            if (BhighestPrice)
                highestPrice = Int32.Parse(sp_highestPrice);
            if (BlowestPrice)
                lowestPrice = Int32.Parse(sp_lowestPrice);

            var q = from s in db.SanPhams.Include(s => s.HangSanXuat).Include(s => s.LoaiSanPham).Include(s => s.TinhTrangSanPham)
                    select s;

            if (Btype)
            {
                var tempP = from s in q
                            where s.sp_type == type
                            select s;
                q = tempP;
            }
           
            if (Bstatus)
            {
                var tempP = from s in q
                            where s.sp_status == status
                            select s;
                q = tempP;
            }

            if (Bproducer)
            {
                var tempP = from s in q
                            where s.sp_producer == producer
                            select s;
                q = tempP;
            }

            if (BhighestPrice)
            {
                var tempP = from s in q
                            where s.sp_price <= highestPrice
                            select s;
                q = tempP;
            }

            if (BlowestPrice)
            {
                var tempP = from s in q
                            where s.sp_price >= lowestPrice
                            select s;
                q = tempP;
            }

            if (!String.IsNullOrEmpty(keyWord))
            {
                q = q.Where(s => s.sp_name.ToUpper().Contains(keyWord.ToUpper())
                                       || s.sp_desription.ToUpper().Contains(keyWord.ToUpper()));
            }

            return View(q.ToList());
        }
    }
}

MobileStoreWebsite/MobileSoreWebsite/Views/Search/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Search</h2>
 
@using (Html.BeginForm("Result", "Search", FormMethod.Get))
{
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>SanPham</legend>
    
        <div class="editor-label">
            @Html.Label("Search")
        </div>
        <div class="editor-field">
            <input type="text" name="keyWord">
        </div>

        <div class="editor-label">
            @Html.Label("Giá từ")
        </div>
        <div class="editor-field">
            <input type="text" name="sp_lowestPrice">
        </div>
        <div class="editor-label">
            @Html.Label("Đến")
        </div>
        <div class="editor-field">
            <input type="text" name="sp_highestPrice">
        </div>

        <div class="editor-label">
            @Html.Label("Loại sản phẩm")
        </div>
        <div class="editor-field">
            @Html.DropDownList("sp_type", String.Empty)
        </div>

        <div class="editor-label">
            @Html.Label("Nhà sản xuất")
        </div>
        <div class="editor-field">
            @Html.DropDownList("sp_producer", String.Empty)
        </div>

          <div class="editor-label">
            @Html.Label("Tình trạn sản phẩm")
        </div>
        <div class="editor-field">
            @Html.DropDownList("sp_status", String.Empty)
        </div>
        <p>
            <input type="submit" value="Search" />
        </p>
    </fieldset>
}

MobileStoreWebsite/MobileSoreWebsite/Views/Search/Result.cshtml
@model IEnumerable<MobileStoreBLL.SanPham>

@{
    ViewBag.Title = "Result";
}
<h2>Kết quả</h2>
<head>

  <meta charset="utf-8" />
  <!-- Set the viewport width to device width for mobile -->
  <meta name="viewport" content="width=device-width" />
    <title>Sản Phẩm</title>
  <!-- Included CSS Files (Compressed) -->

  <script src="~/Scripts/modernizr.foundation.js"></script>
  
  <link rel="stylesheet" href="~/Content/themes/ligature.css">
  
  <!-- Google fonts -->
  <link href='http://fonts.googleapis.com/css?family=Open+Sans+Condensed:300|Playfair+Display:400italic' rel='stylesheet' type='text/css' />

  <!-- IE Fix for HTML5 Tags -->
  <!--[if lt IE 9]>
    <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->

</head>
<body>
        <section class="section_light">
      
      <div class="row">

		<div id="container">
        @if (Model != null)
        {
            foreach (var i in Model) 
            {
		    	<!-- photo -->
		    	<div class='box photo col2'>
		    		<a href="#"><img src="@Url.Content(@i.sp_imgLink)" alt="desc" /></a>
                    <h4 style="text-align:center"><strong>@i.sp_name</strong></h4>
                    <p>@i.sp_price</p>
                    <p>@Html.ActionLink("Details", "Details", new {  id=i.sp_id  })</p> 
		    	</div>
            }   
	    }
        else
        {
            <span> không có kết quả</span>
        }
		</div> <!-- end Masonry container -->
		</div>
        </section>
    <p>
    @Html.ActionLink("Create New", "Create")
</p>

</body>