MobileStoreWebsite/MobileSoreWebsite/Controllers/SanPhamController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MobileStoreBLL;
using MobileStoreBLL.BLL;
using MobileStoreBLL.ViewModel;

namespace MobileSoreWebsite.Controllers
{
    public class SanPhamController : Controller
    {
        private SanPhamBLL spBLL = new SanPhamBLL();
        private CommentBLL cmBLL = new CommentBLL();
        //
        // GET: /SanPham/

        public ActionResult Index()
        {
            //var sanphams = db.SanPhams.Include(s => s.HangSanXuat).Include(s => s.LoaiSanPham).Include(s => s.TinhTrangSanPham);
            return View(spBLL.List());
        }

        //
        // GET: /SanPham/Details/5

        public ActionResult Details(int id = 0)
        {
            SanPham sanpham = spBLL.Details(id);
            sanpham.BinhLuans = cmBLL.ToList(id);
            return View(sanpham);
        }

        //
        // GET: /SanPham/Create

        public ActionResult Create()
        {
            ChiTietSanPham ctsp= spBLL.Create();
            ViewBag.sp_producer = new SelectList(ctsp.DSHangSanXuat, "hsx_id", "hsx_name");
            ViewBag.sp_type = new SelectList(ctsp.DSLoaiSanPham, "lsp_id", "lsp_name");
            ViewBag.sp_status = new SelectList(ctsp.DSTinhTrangSanPham, "tt_id", "tt_name");
            return View();
        }

        //
        // POST: /SanPham/Create

        [HttpPost]
        public ActionResult Create(SanPham sanpham)
        {
            if (ModelState.IsValid)
            {
                spBLL.Create(sanpham);
                return RedirectToAction("Index");
            }

            ChiTietSanPham ctsp = spBLL.Create();
            ViewBag.sp_producer = new SelectList(ctsp.DSHangSanXuat, "hsx_id", "hsx_name");
            ViewBag.sp_type = new SelectList(ctsp.DSLoaiSanPham, "lsp_id", "lsp_name");
            ViewBag.sp_status = new SelectList(ctsp.DSTinhTrangSanPham, "tt_id", "tt_name");
            return View(sanpham);
        }

        //
        // GET: /SanPham/Edit/5

        public ActionResult Edit(int id = 0)
        {
            SanPham sanpham = spBLL.Details(id);
            if (sanpham == null)
            {
                return HttpNotFound();
            }
            ChiTietSanPham ctsp = spBLL.Create();
            ViewBag.sp_producer = new SelectList(ctsp.DSHangSanXuat, "hsx_id", "hsx_name");
            ViewBag.sp_type = new SelectList(ctsp.DSLoaiSanPham, "lsp_id", "lsp_name");
            ViewBag.sp_status = new SelectList(ctsp.DSTinhTrangSanPham, "tt_id", "tt_name");
            return View(sanpham);
        }

        //
        // POST: /SanPham/Edit/5

        [HttpPost]
        public ActionResult Edit(SanPham sanpham)
        {
            if (ModelState.IsValid)
            {
                spBLL.Eidit(sanpham);
            }
            ChiTietSanPham ctsp = spBLL.Create();
            ViewBag.sp_producer = new SelectList(ctsp.DSHangSanXuat, "hsx_id", "hsx_name");
            ViewBag.sp_type = new SelectList(ctsp.DSLoaiSanPham, "lsp_id", "lsp_name");
            ViewBag.sp_status = new SelectList(ctsp.DSTinhTrangSanPham, "tt_id", "tt_name");
            return RedirectToAction("Index");// View(sanpham);
        }

        [HttpPost]
        public ActionResult UpdateComment(string user, string content, int id)
        {
            //cmBLL.Add(id, content, user); 
            BinhLuan bl = new BinhLuan();
            bl.bl_name  = user;
            bl.bl_sanPham = id;
            bl.bl_content = content;
            bl.bl_datetime = DateTime.Now;
            cmBLL.Add(bl);
            return Json("binh luan da luu tru",JsonRequestBehavior.AllowGet);
        }
        //
        // GET: /SanPham/Delete/5

        public ActionResult Delete(int id = 0)
        {
            SanPham sanpham = spBLL.Details(id);
            if (sanpham == null)
            {
                return HttpNotFound();
            }
            return View(sanpham);
        }

        //
        // POST: /SanPham/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            spBLL.Delete(id);
            return RedirectToAction("Index");
        }
    }
}

MobileStoreWebsite/MobileSoreWebsite/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7]> <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js lt-ie9 lt-ie8" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js lt-ie9" lang="en"> <![endif]-->
<!--[if gt IE 8]><!--> 
<html class="no-js" lang="vi"> <!--<![endif]-->

<head>

  <meta charset="utf-8" />
  <!-- Set the viewport width to device width for mobile -->
  <meta name="viewport" content="width=device-width" />

  <title>Website for Mobile Phone</title>
  <link rel="stylesheet" href="~/Content/themes/trangchu.css">
  <!-- Included CSS Files (Compressed) -->
@Styles.Render("~/Content/css")
@*@Scripts.Render("~/bundles/js")*@
@Scripts.Render("~/bundles/jquery")
  <script src="http://code.jquery.com/jquery-latest.min.js"></script>
  <!-- Google fonts -->
  <link href='http://fonts.googleapis.com/css?family=Open+Sans+Condensed:300|Playfair+Display:400italic' rel='stylesheet' type='text/css' />
  <!-- IE Fix for HTML5 Tags -->
  <!--[if lt IE 9]>
    <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->
</head>

<body>

<!-- ######################## Main Menu ######################## -->
 
	<nav>

     <div class="twelve columns header_nav">
     <div class="row">
      
        <ul id="menu-header" class="nav-bar horizontal">
        
         <li class=""><a href="@Url.Action("Index","Home")">Trang chủ</a></li>
      
           <li class="has-flyout">
           <a>@Html.ActionLink("Sản Phẩm","index","SanPham")</a><a href="#" class="flyout-toggle"></a>
            <ul class="flyout"><!-- Flyout Menu -->
              <li class="has-flyout"><a href="Nokia.html">Nokia</a></li>
              <li class="has-flyout"><a href="SamSung.html">SamSung</a></li>
              <li class="has-flyout"><a href="Apple.html">Apple</a></li>
              <li class="has-flyout"><a href="Apple.html">Others</a></li>
             
            </ul> 
          </li><!-- END Flyout Menu -->
      
          <li class=""><a href="#">Tìm kiếm</a></li>
		  <li class=""><a href="@Url.Action("Contact","Home")">Giới thiệu - Liên Hệ</a></li>
		   <li class=""><a href="Register.html">Đăng nhập - Đăng kí</a></li>
			
      
        </ul>
        
      </div>  
      </div>
      
	</nav>
	<!-- ######################## Header ######################## -->
     @RenderBody()
       @* <header>
              <h1 class="heading_supersize">TNT STORE</h1>
              <h2 class="welcome_text">Website dành cho các thiết bị di động </h2>    
        </header>*@
    <!-- ######################## Slider ######################## -->
	@*<div id="slides">
		<img src=@Url.Content("~/Images/iphone.jpg")>
		<img src=@Url.Content("~/Images/SamSung.jpg")>
		<img src=@Url.Content("~/Images/Nokia.png")>
		<img src=@Url.Content("~/Images/ipad.png")>
		<img src=@Url.Content("~/Images/macbook.jpg")>
		      <a href="#" class="slidesjs-previous slidesjs-navigation"><i class="icon-chevron-left icon-large"></i></a>
      <a href="#" class="slidesjs-next slidesjs-navigation"><i class="icon-chevron-right icon-large"></i></a>
	</div>*@
	<!-- ######################## Footer ######################## -->
	<div class ="fo">
		<h3 class = "welcome_text">Cám ơn sự ghé thăm của quý khách</h3>
		<h3 id = "design">Design by Lâm Phong Thạnh - 1012407</h3>
	</div>
    <script type="text/javascript" src="~/Scripts/foundation.min.js"></script>
	<script type="text/javascript" src="~/Scripts/app.js"></script>
	<script src="~/Scripts/jquery.slides.min.js"></script>
	<script type="text/javascript">
		$(function(){
		  $("#slides").slidesjs({
			width: 1000,
			height: 528,
			navigation: false,
			play: {
			  active: true,
			  auto: true,
			  interval: 4000,
			  swap: true
			}
		  });
		});
	 </script>
    @RenderSection("scripts", required: false)
</body>
</html>